FROM python:3.8-alpine

WORKDIR /usr/src/app

ENV IP="127.0.0.1:8000"

COPY . .
RUN echo "http://dl-8.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN echo "http://dl-8.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
ENV PYTHONPATH /usr/lib/python3.8/site-packages

RUN apk update
RUN apk add make automake gcc g++ python3-dev
RUN python -m pip install --upgrade pip
RUN apk add py3-numpy py3-pandas

CMD [ "python", "./manage.py", "runserver", "${IP}" ]