# Generated by Django 3.2.5 on 2021-10-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=90)),
                ('order_type', models.CharField(max_length=10)),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=2)),
                ('lang', models.CharField(default='python', max_length=10)),
                ('start_time', models.DateTimeField(null=True, verbose_name='%Y-%m-%d %H:%M:%S')),
                ('end_time', models.DateTimeField(null=True, verbose_name='%Y-%m-%d %H:%M:%S')),
                ('cur_time', models.DateTimeField(null=True, verbose_name='%Y-%m-%d %H:%M:%S')),
                ('create_time', models.DateTimeField(null=True, verbose_name='%Y-%m-%d %H:%M:%S')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='%Y-%m-%d %H:%M:%S')),
            ],
            options={
                'db_table': 'cl_order',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=90)),
                ('code', models.CharField(max_length=10)),
                ('lang', models.CharField(default='python', max_length=10)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cl_strategy',
            },
        ),
    ]
