# Generated by Django 3.2.5 on 2021-10-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=90)),
                ('stock_id', models.CharField(max_length=10)),
                ('trade_type', models.CharField(max_length=10)),
                ('origin_position', models.IntegerField()),
                ('origin_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cur_position', models.IntegerField()),
                ('cur_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin_funds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cur_funds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_equity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cl_gain',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('log', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cl_log',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=90)),
                ('stock_id', models.CharField(max_length=10)),
                ('trade_type', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=2)),
                ('trade_time', models.DateTimeField(auto_now_add=True)),
                ('trade_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.IntegerField()),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cur_funds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin_funds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('after_position', models.IntegerField()),
                ('before_position', models.IntegerField()),
                ('is_success', models.CharField(default='Y', max_length=1)),
                ('order_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cl_trade',
            },
        ),
        migrations.CreateModel(
            name='UserSub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=90)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('valid', models.CharField(max_length=1)),
                ('order_id', models.IntegerField()),
            ],
            options={
                'db_table': 'cl_user_sub',
            },
        ),
    ]
