# Generated by Django 3.2.5 on 2021-10-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=90, unique=True)),
                ('stock_id', models.CharField(max_length=20)),
                ('trade_type', models.CharField(max_length=10)),
                ('origin_position', models.IntegerField(null=True)),
                ('origin_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cur_position', models.IntegerField(null=True)),
                ('cur_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('origin_funds', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cur_funds', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('current_equity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cl_gain',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=90)),
                ('stock_id', models.CharField(max_length=20)),
                ('trade_type', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=2, null=True)),
                ('bs_time', models.DateTimeField(null=True)),
                ('level', models.CharField(max_length=10)),
                ('trade_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('trade_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit', models.IntegerField(null=True)),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cur_funds', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('origin_funds', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('after_position', models.IntegerField(null=True)),
                ('before_position', models.IntegerField(null=True)),
                ('is_success', models.CharField(default='Y', max_length=1, null=True)),
                ('reason', models.CharField(max_length=90, null=True)),
            ],
            options={
                'db_table': 'cl_trade',
            },
        ),
    ]
